# Service Manifest
# kubectl port-forward service/vat-svc 30001:80
apiVersion: v1
kind: Service
metadata:
  name: vat-svc
  labels:
    app: vat-calc
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
    protocol: TCP
  selector:
    app: vat-calc
---
# Deployment Manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vat-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vat-calc
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: vat-calc
    spec:
      containers:
      - name: vat-pod
        image: victorialloyd/vat-calculator:latest
        ports:
        - containerPort: 80
